import type { Metadata } from "next"
import localFont from "next/font/local"
import "app/sass/globals.sass"

const figtreeItalic = localFont({
  src: "./fonts/Figtree-Italic-VariableFont_wght.ttf",
  variable: "--font-figtree-italic",
  weight: "500 800",
});
const figtree = localFont({
  src: "./fonts/Figtree-VariableFont_wght.ttf",
  variable: "--font-figtree",
  weight: "500 800",
});

export const metadata: Metadata = {
  title: "Blog Preview Card",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${figtreeItalic.variable} ${figtree.variable}`}>
        {children}
      </body>
    </html>
  );
}
